version: '2.2'
services:
  mysqls:
    image: 'mysql:latest'
    restart: always
    volumes:
      - './mysql_fintech_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=892bwi
    ports:
      - '3306:3306'